description: "Monis is a hyper-fast light-weight SSG written in Crystal."
author: "Raleigh Wise"
url: "https://raleighwi.se/monis"
image: "https://cloud-kk3xz9mty-hack-club-bot.vercel.app/0untitled-artwork.png"